version: '3'

services:
  app-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
