version: '3'

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  redis:
    image: redis:7.0.12
